---
proxy-providers:
  VIP-FR:
    type: http
    path: "./proxy_provider/Akun/VIP-FR.yaml"
    url: https://raw.githubusercontent.com/GetPush/getpush.github.io/master/remote/proxy_provider/Akun/AK-FR.yaml
    health-check:
      enable: true
    interval: 86400
  VIP-NL:
    type: http
    path: "./proxy_provider/Akun/VIP-NL.yaml"
    url: https://raw.githubusercontent.com/GetPush/getpush.github.io/master/remote/proxy_provider/Akun/AK-NL.yaml
    health-check:
      enable: true
    interval: 86400
  VIP-SG:
    type: http
    path: "./proxy_provider/Akun/VIP-SG.yaml"
    url: https://raw.githubusercontent.com/GetPush/getpush.github.io/master/remote/proxy_provider/Akun/AK-SG.yaml
    health-check:
      enable: true
    interval: 86400
  VIP-US:
    type: http
    path: "./proxy_provider/Akun/VIP-US.yaml"
    url: https://raw.githubusercontent.com/GetPush/getpush.github.io/master/remote/proxy_provider/Akun/AK-US.yaml
    health-check:
      enable: true
    interval: 86400

###################### TROJAN ###################
  TR-SGHE1:
    type: http
    path: "./proxy_provider/Trojan/SGHE1.yaml"
    url: https://raw.githubusercontent.com/GetPush/getpush.github.io/master/remote/proxy_provider/Trojan/SGHE1.yaml
    health-check:
      enable: true
    interval: 86400
  TR-SGHE2:
    type: http
    path: "./proxy_provider/Trojan/SGHE2.yaml"
    url: https://raw.githubusercontent.com/GetPush/getpush.github.io/master/remote/proxy_provider/Trojan/SGHE2.yaml
    health-check:
      enable: true
    interval: 86400
  TR-SGHE3:
    type: http
    path: "./proxy_provider/Trojan/SGHE3.yaml"
    url: https://raw.githubusercontent.com/GetPush/getpush.github.io/master/remote/proxy_provider/Trojan/SGHE3.yaml
    health-check:
      enable: true
    interval: 86400
  TR-SGMELBI:
    type: http
    path: "./proxy_provider/Trojan/SGMELBI.yaml"
    url: https://raw.githubusercontent.com/GetPush/getpush.github.io/master/remote/proxy_provider/Trojan/SGMELBI.yaml
    health-check:
      enable: true
    interval: 86400


proxy-groups:
- name: CLASH FOCUS
  type: select
  proxies:
  - CLASH BOOST
  - ASIA
  - EROPA
  - AMERICA
  - Trojan
  - DIRECT
  url: https://cp.cloudflare.com/generate_204
  interval: '150'
- name: CLASH BOOST
  type: fallback
  lazy: true
  disable-udp: false
  proxies:
  - ASIA
  - EROPA
  - AMERICA
  - Trojan
  - DIRECT
  url: https://cp.cloudflare.com/generate_204
  interval: '30'

- name: IKLAN
  type: select
  disable-udp: false
  proxies:
  - CLASH FOCUS
  - REJECT
- name: TrafficPorn
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - CLASH FOCUS

- name: ASIA
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - VIP-SG
  url: https://cp.cloudflare.com/generate_204
  interval: '150'
- name: AMERICA
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - VIP-US
  url: https://cp.cloudflare.com/generate_204
  interval: '150'
- name: EROPA
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - VIP-FR
  - VIP-NL
  url: https://cp.cloudflare.com/generate_204
  interval: '150'
- name: Trojan
  type: url-test
  strategy: round-robin
  disable-udp: false
  use:
  - TR-SGHE1
  - TR-SGHE2
  - TR-SGHE3
  - TR-SGMELBI
  url: https://cp.cloudflare.com/generate_204
  interval: '600'

rule-providers:
#─────────────────◉ For WARNET ◉─────────────────
  rule_falsepositive:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_falsepositive.yaml
    path: "./rule_provider/rule_falsepositive.yaml"
    interval: 86400
  rule_playstore:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_playstore.yaml
    path: "./rule_provider/rule_playstore.yaml"
    interval: 86400
  rule_umum:
    type: file
    behavior: classical
    path: "./rule_provider/rule_umum.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_umum.yaml
    interval: 86400

  d3ward:
    type: file
    behavior: domain
    path: "./rule_provider/d3ward.yaml"
  rule_clash:
    type: file
    behavior: domain
    path: "./rule_provider/rule_clash.yaml"
    health-check:
      enable: true
    url: https://raw.githubusercontent.com/GetPush/getpush.github.io/master/remote/rule_provider/rule_clash.yaml
  Direct:
    type: file
    behavior: classical
    path: "./rule_provider/direct.yaml"
    health-check:
      enable: true
    url: https://raw.githubusercontent.com/GetPush/getpush.github.io/master/remote/rule_provider/direct.yaml
  rule_lancidr:
    type: file
    behavior: ipcidr
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_lancidr.yaml
    path: "./rule_provider/rule_lancidr.yaml"
    interval: 86400
  rule_malicious:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_malicious.yaml
    path: "./rule_provider/rule_malicious.yaml"
    interval: 43200
  rule_maliciousip:
    type: file
    behavior: ipcidr
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_maliciousip.yaml
    path: "./rule_provider/rule_maliciousip.yaml"
    interval: 43200
  rule_personalads:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_personalads.yaml
    path: "./rule_provider/rule_personalads.yaml"
    interval: 86400
  rule_basicads:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_basicads.yaml
    path: "./rule_provider/rule_basicads.yaml"
    interval: 43200
  rule_hijacking:
    type: file
    behavior: classical
    path: "./rule_provider/rule_hijacking.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_hijacking.yaml
    interval: 86400
  rule_privacy:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_privacy.yaml
    path: "./rule_provider/rule_privacy.yaml"
    interval: 86400
  rule_porn:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_porn.yaml
    path: "./rule_provider/rule_porn.yaml"
    interval: 86400
  rule_nsfw:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_nsfw.yaml
    path: "./rule_provider/rule_nsfw.yaml"
    interval: 43200

rules:
  ## block ads
- DOMAIN-SUFFIX,googlesyndication.com,IKLAN
- DOMAIN-SUFFIX,pagead2.googlesyndication.com,REJECT
- DOMAIN-SUFFIX,pagead2.googleadservices.com,REJECT
- DOMAIN-SUFFIX,afs.googlesyndication.com,REJECT
- DOMAIN-SUFFIX,analytics.google.com,REJECT
- DOMAIN-SUFFIX,udcm.yahoo.com,REJECT

- AND,((GEOSITE,category-ads-all),(NOT,((DOMAIN-SUFFIX,googlesyndication.com)))),IKLAN
- GEOSITE,category-ads-all,IKLAN

  ## direct FCM
- AND,((NETWORK,TCP),(DST-PORT,5228-5230)),DIRECT
- AND,((NETWORK,TCP),(DST-PORT,5228-5230),(OR,((DOMAIN-KEYWORD,google)))),DIRECT
 
  ## block udp/quic YouTube
- AND,((NETWORK,udp),(OR,((DST-PORT,443/80),(GEOSITE,youtube)))),REJECT
- AND,((NETWORK,udp),(GEOSITE,youtube)),REJECT


  # # fix dnsleak
- IP-CIDR,127.0.0.1/32,REJECT,no-resolve
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- IP-CIDR,28.0.0.1/8,REJECT,no-resolve
- IP-CIDR6,::1/128,REJECT,no-resolve

  ## rules telegram
- GEOIP,telegram,CLASH FOCUS
- GEOSITE,telegram,CLASH FOCUS

  ## direct ntp
- AND,((NETWORK,UDP),(DST-PORT,123)),DIRECT
- DST-PORT,123/136/137-139,DIRECT,udp

  ## rules inner, recommended untuk non kuota reguler
- AND,((PROCESS-NAME,clash),(NOT,((IN-TYPE,inner)))),REJECT
- IN-TYPE,inner,CLASH FOCUS


 ## final
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT

#- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- DST-PORT,22,DIRECT

- RULE-SET,rule_clash,REJECT
- RULE-SET,Direct,DIRECT

- RULE-SET,rule_lancidr,DIRECT,no-resolve
- RULE-SET,rule_falsepositive,CLASH FOCUS
- RULE-SET,rule_malicious,REJECT
- RULE-SET,rule_maliciousip,REJECT
- RULE-SET,rule_personalads,IKLAN
- RULE-SET,rule_basicads,IKLAN
- RULE-SET,rule_hijacking,IKLAN
- RULE-SET,rule_privacy,IKLAN
- RULE-SET,rule_porn,TrafficPorn
- RULE-SET,rule_nsfw,TrafficPorn
- RULE-SET,rule_playstore,CLASH FOCUS
- RULE-SET,rule_umum,CLASH FOCUS

- DST-PORT,9993,GLOBAL
- RULE-SET,d3ward,IKLAN
- GEOSITE,oisd-full,IKLAN
- GEOSITE,rule-ads,IKLAN
- DOMAIN-KEYWORD,pagead2.googlesyndication.com,GLOBAL
- MATCH,GLOBAL


port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
mode: rule
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
secret: TopPay
bind-address: "*"
unified-delay: true
external-ui: "/usr/share/openclash/ui"
experimental:
  ignore-resolve-fail: true
ipv6: false

dns:
  enable: true
  ipv6: true
  default-nameserver:
    # cloudflare
    - 1.1.1.1
    - 114.114.114.114
    # google
    - 8.8.8.8
    - tls://223.5.5.5:853
    - https://223.5.5.5/dns-query
  listen: 0.0.0.0:7874
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "*.n.n.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - time-ios.apple.com
  - shark007.net

# setting dns publik / dns leak
  nameserver:
     - https://dns.bebasid.com/dns-query
     - tls://dns.bebasid.com
  #  - 1.1.1.1
  #  - 9.9.9.9
    # google
  #  - 8.8.8.8
  #  - 1.0.0.1

  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - 'tls://dns.google#proxy'


  nameserver-policy:
     'www.baidu.com': '114.114.114.114'
     '+.internal.crop.com': '10.0.0.1'
     'geosite:cn': https://doh.pub/dns-query

  fallback:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - tls://8.8.4.4
    - tls://1.1.1.1

  fallback-filter:
  geoip: true
  geoip-code: ID
  geosite:
    - gfw
  ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
  domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "+.*"

tun:
  enable: true
  stack: system
  device: utun
  mtu: 65535
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
    - any:53
    - tcp://any:53

profile:
  store-selected: true
  store-fakeip: true
  store-fake-ip: false

geodata-mode: false
geodata-loader: memconservative
sniffer:
  enable: false
  force-dns-mapping: false
  parse-pure-ip: false
  override-destination: false 
  sniffing:
    - tls
    - http

  force-domain:
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssott.com"
  - +.v2ex.com
  skip-domain:
  - "+.apple.com"
  - Mijia Cloud
  - "+.jd.com"
  port-whitelist:
  - 443
  - 80