proxies:
  - name: service 
    server: www.google.com
    port: 80
    type: vmess
    uuid: 0.0.0.0
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: 0.0.0.0
    network: ws
    ws-opts:
      path: /v2ray
      headers:
        Host: sg1-v2ray.sshkit.org
