proxies:
  - name: service 1 #
    server: 104.19.142.89
    port: 80
    type: vless
    uuid: ec2be492-85a1-40ca-8165-5225255f4f61
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: us1.v2vless.xyz
    network: ws
    ws-opts:
      path: /vless
      headers:
        Host: us1.v2vless.xyz
    udp: true

:
  - name: service 2 #
    server: 104.19.142.89
    port: 80
    type: vless
    uuid: ff8b0e81-449f-485b-9369-1ea8cdde0675
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: us2.v2vless.xyz
    network: ws
    ws-opts:
      path: /vless
      headers:
        Host: us2.v2vless.xyz
    udp: true


  - name: service 3 #
    server: 104.16.108.96
    port: 80
    type: vmess
    uuid: e377d03a-4b3f-46b1-9199-46f769d8367a
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: us2.v2rayserv.com
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: us2.v2rayserv.com
    udp: true


  - name: service 4 #
    server: 104.19.142.89
    port: 80
    type: vmess
    uuid: e377d03a-4b3f-46b1-9199-46f769d8367a
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: us2.v2rayserv.com
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: us2.v2rayserv.com
    udp: true

