proxies:
  - name: service 1 #
    server: 104.16.108.96
    port: 80
    type: vmess
    uuid: 0c4c6d70-95aa-4d70-8880-ea43d6b48741
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: us1.v2rayserv.com
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: us1.v2rayserv.com
    udp: true

:
  - name: service 2 #
    server: 104.19.142.89
    port: 80
    type: vmess
    uuid: 0c4c6d70-95aa-4d70-8880-ea43d6b48741
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: us1.v2rayserv.com
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: us1.v2rayserv.com
    udp: true


  - name: service 3 #
    server: 104.16.108.96
    port: 80
    type: vmess
    uuid: e377d03a-4b3f-46b1-9199-46f769d8367a
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: us2.v2rayserv.com
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: us2.v2rayserv.com
    udp: true


  - name: service 4 #
    server: 104.19.142.89
    port: 80
    type: vmess
    uuid: e377d03a-4b3f-46b1-9199-46f769d8367a
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: us2.v2rayserv.com
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: us2.v2rayserv.com
    udp: true

