proxies:
  - name: service 1 #
    server: 104.19.142.89
    port: 80
    type: vmess
    uuid: c6747da4-fb2e-4a2a-bdb7-8614bdd6b0b3
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sg4-v2ray.sshkit.org
    network: ws
    ws-opts:
      path: /sshkit/1828396894/649af9079e002/
      headers:
        Host: sg4-v2ray.sshkit.org
    udp: true


  - name: service 2 #
    server: 104.19.142.89
    port: 80
    type: vmess
    uuid: aa721960-2332-11ee-b231-205c6d5f5d78
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: id-1.0rd.net
    network: ws
    ws-opts:
      path: /ehcsn9kp
      headers:
        Host: id-1.0rd.net
    udp: true


  - name: service 3 #
    server: 104.19.142.89
    port: 80
    type: vmess
    uuid: aa721960-2332-11ee-b231-205c6d5f5d78
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: id-1.0rd.net
    network: ws
    ws-opts:
      path: /ehcsn9kp
      headers:
        Host: id-1.0rd.net
    udp: true


  - name: service 4 #
    server: 104.19.142.89
    port: 80
    type: vmess
    uuid: aa721960-2332-11ee-b231-205c6d5f5d78
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: id-1.0rd.net
    network: ws
    ws-opts:
      path: /ehcsn9kp
      headers:
        Host: id-1.0rd.net
    udp: true


  - name: service 5 #
    server: 104.19.142.89
    port: 80
    type: vmess
    uuid: aa721960-2332-11ee-b231-205c6d5f5d78
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: id-1.0rd.net
    network: ws
    ws-opts:
      path: /ehcsn9kp
      headers:
        Host: id-1.0rd.net
    udp: true
