proxies:
  - name: service 1 #
    server: 104.19.142.89
    port: 80
    type: vless
    uuid: ec2be492-85a1-40ca-8165-5225255f4f61
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: us1.v2vless.xyz
    network: ws
    ws-opts:
      path: /vless
      headers:
        Host: us1.v2vless.xyz
    udp: true


  - name: service 2 #
    server: 104.19.142.89
    port: 80
    type: vless
    uuid: ff8b0e81-449f-485b-9369-1ea8cdde0675
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: us2.v2vless.xyz
    network: ws
    ws-opts:
      path: /vless
      headers:
        Host: us2.v2vless.xyz
    udp: true


  - name: service 3 #
    server: 104.16.108.96
    port: 80
    type: vmess
    uuid: 9a8d80b8-5daf-43ff-93d1-a2c835b3e490
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: us5vm.xservs.xyz
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: us5vm.xservs.xyz
    udp: true


  - name: service 4 # Vmess Netherlands 2 2023-07-26
    server: 104.19.142.89
    port: 80
    type: vmess
    uuid: 58c964e0-25ee-11ee-b436-205c6d5f5d78
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: nl-2.0rd.net
    network: ws
    ws-opts:
      path: /6dn9lixu
      headers:
        Host: nl-2.0rd.net
    udp: true

