proxies:
  - name: layanan alt
    server: layanan.ruangguru.com
    port: 80
    type: vmess
    uuid: 5c26e150-03cf-11ee-b836-205c6d5f5d78
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sg-8.0rd.net
    network: ws
    ws-opts:
      path: /l2ujo3mp
      headers:
        Host: sg-8.0rd.net
    udp: true
  - name: 1GB Day v1
    server: 104.16.108.96
    port: 80
    type: vmess
    uuid: 5c26e150-03cf-11ee-b836-205c6d5f5d78
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sg-8.0rd.net
    network: ws
    ws-opts:
      path: /l2ujo3mp
      headers:
        Host: sg-8.0rd.net
    udp: true
